[features]
seeds = false
[programs.localnet]
angus = "HAV4YnfHKvsS31VmcBuwDEGR93zGKanjuzw11YAN3xwB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "$HOME/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
